### PR TITLE
Missing mouseup after blur

### LINKED ISSUE #71: [BUG] Missing mouseup after blur
**Describe the bug**
When I am in browser and I try to switch window on my host PC, I press Alt+Tab. It works great. But when I come back to neko, I notice, that there is Alt pressed. It captures `mousedown` on Alt key, and then leaves session. So no `mouseup` for Alt will be distributed.

**To Reproduce**
1. Go to neko.
2. Put your cursor in neko-shared-browser-window.
3. Press Alt+Tab.
4. Go back to neko (by pressing Alt+Tab again).
5. Put your cursor in browser.
6. Scroll mouse. Now it should switch screens.
7. Press again Alt, and it will be normalized.

This will most likely visible only with Alt+Tab, but is issue with every key. 
1. Go to neko.
2. Put your cursor in browsers searchbar.
3. Press down some key (e.g. W).
4. Move cursour out of neko-shared-browser-window (to chat for example).
5. There should be still be typing that key, because no mouse-down event was sent.

**Expected behavior**
If i press any key and leave neko-shared-browser-window with cursor (or with bluring my host window with Alt+Tab), it should "release" pressed key - send `mouseup` event.

**Screenshots**
image

**Desktop**
 - OS: Win10
 - Browser Chrome 80
 - Version 2

Anyway, I would say, there should be only one Desktop, since only that is used now. Or are some use-cases for other desktops?

https://github.com/nurdism/neko/blob/14caa1fba8e04435588432d348684c5fa0b47164/.docker/files/openbox.xml#L147

### PR DESCRIPTION
**Pull request by m1k1o**
Fixes https://github.com/nurdism/neko/issues/71.

Most likely will be only one key in object before leaving with Alt+Tab, but for the sake of completeness I added object for multiple, which can be accessed in O(1).

### CODE REVIEW

File: client/src/components/video.vue [hunk 1]
```diff
@@ -401,6 +404,18 @@
       }
     }
 
+    onBlur() {
+      if (!this.focused || !this.hosting || this.locked) {
```
Comment (nurdism) [inline client/src/components/video.vue:408]: shouldn't this be `this.focused` vs `!this.focused`? did you test if it works?

Comment (m1k1o) [reply client/src/components/video.vue:408]: Tested. It works in Chrome & Firefox, appearently it is called in right order. According to docs, it seems it fires before `onMouseLeave` that sets `focused` to `false`.

> The [focusout ](https://developer.mozilla.org/en-US/docs/Web/API/Element/focusout_event) event fires when an element **is about to lose focus**. The main difference between this event and blur is that focusout bubbles while blur does not.


It should only send those keys, when cursor is in browser - so browser is focused and listenting for keys. It sould not send keys, when I am e.g. with cursor in chat, but have active keyboard and I press `Alt+Tab`.

Comment (nurdism) [reply client/src/components/video.vue:408]: awesome looks good to me then
